// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package artifactImport

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	ArtifactoryToken    *string `mapstructure:"artifactory_token" required:"true" cty:"artifactory_token" hcl:"artifactory_token"`
	ArtifactoryServer   *string `mapstructure:"artifactory_server" required:"true" cty:"artifactory_server" hcl:"artifactory_server"`
	VcenterServer       *string `mapstructure:"vcenter_server" required:"true" cty:"vcenter_server" hcl:"vcenter_server"`
	VcenterUser         *string `mapstructure:"vcenter_user" required:"true" cty:"vcenter_user" hcl:"vcenter_user"`
	VcenterPassword     *string `mapstructure:"vcenter_password" required:"true" cty:"vcenter_password" hcl:"vcenter_password"`
	VcenterDatacenter   *string `mapstructure:"datacenter_name" required:"true" cty:"datacenter_name" hcl:"datacenter_name"`
	VcenterDatastore    *string `mapstructure:"datastore_name" required:"true" cty:"datastore_name" hcl:"datastore_name"`
	VcenterCluster      *string `mapstructure:"cluster_name" required:"true" cty:"cluster_name" hcl:"cluster_name"`
	VcenterFolder       *string `mapstructure:"folder_name" required:"false" cty:"folder_name" hcl:"folder_name"`
	VcenterResourcePool *string `mapstructure:"respool_name" required:"false" cty:"respool_name" hcl:"respool_name"`
	OutputDir           *string `mapstructure:"output_dir" required:"false" cty:"output_dir" hcl:"output_dir"`
	DownloadUri         *string `mapstructure:"download_uri" required:"false" cty:"download_uri" hcl:"download_uri"`
	ImportNoDownload    *bool   `mapstructure:"import_no_download" required:"false" cty:"import_no_download" hcl:"import_no_download"`
	SourceImagePath     *string `mapstructure:"source_path" required:"false" cty:"source_path" hcl:"source_path"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"artifactory_token":  &hcldec.AttrSpec{Name: "artifactory_token", Type: cty.String, Required: false},
		"artifactory_server": &hcldec.AttrSpec{Name: "artifactory_server", Type: cty.String, Required: false},
		"vcenter_server":     &hcldec.AttrSpec{Name: "vcenter_server", Type: cty.String, Required: false},
		"vcenter_user":       &hcldec.AttrSpec{Name: "vcenter_user", Type: cty.String, Required: false},
		"vcenter_password":   &hcldec.AttrSpec{Name: "vcenter_password", Type: cty.String, Required: false},
		"datacenter_name":    &hcldec.AttrSpec{Name: "datacenter_name", Type: cty.String, Required: false},
		"datastore_name":     &hcldec.AttrSpec{Name: "datastore_name", Type: cty.String, Required: false},
		"cluster_name":       &hcldec.AttrSpec{Name: "cluster_name", Type: cty.String, Required: false},
		"folder_name":        &hcldec.AttrSpec{Name: "folder_name", Type: cty.String, Required: false},
		"respool_name":       &hcldec.AttrSpec{Name: "respool_name", Type: cty.String, Required: false},
		"output_dir":         &hcldec.AttrSpec{Name: "output_dir", Type: cty.String, Required: false},
		"download_uri":       &hcldec.AttrSpec{Name: "download_uri", Type: cty.String, Required: false},
		"import_no_download": &hcldec.AttrSpec{Name: "import_no_download", Type: cty.Bool, Required: false},
		"source_path":        &hcldec.AttrSpec{Name: "source_path", Type: cty.String, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{}
	return s
}
